/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author albeluiz.santos
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadMotoTaxista = new javax.swing.JMenuItem();
        jMenuItemCadUsuário = new javax.swing.JMenuItem();
        jMenuConsultaLocalidade = new javax.swing.JMenu();
        jMenuItemCabula = new javax.swing.JMenuItem();
        jMenuItemEngomadeira = new javax.swing.JMenuItem();
        jMenuItemEstradadasBarreiras = new javax.swing.JMenuItem();
        jMenuItemSaboeiro = new javax.swing.JMenuItem();
        jMenuItemSaoGonçalo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelFundoPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo principal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(20, 10, 321, 280);

        jMenuCadastro.setText("Cadastro MotoTaxista");

        jMenuItemCadMotoTaxista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadMotoTaxista.setText("Cadastro Moto Taxista");
        jMenuItemCadMotoTaxista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMotoTaxistaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadMotoTaxista);

        jMenuItemCadUsuário.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadUsuário.setText("Cadastro Usuário");
        jMenuItemCadUsuário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuárioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadUsuário);

        jMenuBar1.add(jMenuCadastro);

        jMenuConsultaLocalidade.setText("Consulta Por Localidade");

        jMenuItemCabula.setText("Cabula");
        jMenuConsultaLocalidade.add(jMenuItemCabula);

        jMenuItemEngomadeira.setText("Engomadeira");
        jMenuConsultaLocalidade.add(jMenuItemEngomadeira);

        jMenuItemEstradadasBarreiras.setText("Estrada das Barreiras");
        jMenuConsultaLocalidade.add(jMenuItemEstradadasBarreiras);

        jMenuItemSaboeiro.setText("Saboeiro");
        jMenuConsultaLocalidade.add(jMenuItemSaboeiro);

        jMenuItemSaoGonçalo.setText("São Gonçalo");
        jMenuConsultaLocalidade.add(jMenuItemSaoGonçalo);

        jMenuBar1.add(jMenuConsultaLocalidade);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.setToolTipText("Fechar o Sistema.");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(401, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadMotoTaxistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMotoTaxistaActionPerformed
FormMotoTaxi tela = new FormMotoTaxi();
tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadMotoTaxistaActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
  System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadUsuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuárioActionPerformed
        FormCadastroUsuario tela = new FormCadastroUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadUsuárioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuConsultaLocalidade;
    private javax.swing.JMenuItem jMenuItemCabula;
    private javax.swing.JMenuItem jMenuItemCadMotoTaxista;
    private javax.swing.JMenuItem jMenuItemCadUsuário;
    private javax.swing.JMenuItem jMenuItemEngomadeira;
    private javax.swing.JMenuItem jMenuItemEstradadasBarreiras;
    private javax.swing.JMenuItem jMenuItemSaboeiro;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSaoGonçalo;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables

    
        }
    

